// <auto-generated />
namespace FacultyV3.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Initialize5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialize5));
        
        string IMigrationMetadata.Id
        {
            get { return "202003031621522_Initialize5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
